INSERT INTO puzzles (slug, title, description, difficulty, player_color, initial_board, solution, hint, created_at, updated_at) VALUES
('back-rank-mate-1', 'Back Rank Mate', 'White to move. Deliver checkmate on the back rank.', 'beginner', 'white', '[[null,null,null,null,{"type":"king","color":"black","hasMoved":true},null,null,null],[null,null,null,{"type":"pawn","color":"black","hasMoved":true},{"type":"pawn","color":"black","hasMoved":true},{"type":"pawn","color":"black","hasMoved":true},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[{"type":"rook","color":"white","hasMoved":true},null,null,null,null,null,{"type":"king","color":"white","hasMoved":true},null]]', '[{"from":"a1","to":"a8"}]', '{"pieceSquare":{"row":7,"col":0},"targetSquare":{"row":0,"col":0}}', datetime('now'), datetime('now')),
('smothered-mate-1', 'Smothered Mate', 'White to move. The knight delivers a smothered mate — the king is trapped by its own pieces.', 'beginner', 'white', '[[null,null,null,null,null,null,{"type":"rook","color":"black","hasMoved":true},{"type":"king","color":"black","hasMoved":true}],[null,null,null,null,null,null,{"type":"pawn","color":"black","hasMoved":true},{"type":"pawn","color":"black","hasMoved":true}],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"type":"knight","color":"white","hasMoved":true},null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,{"type":"king","color":"white","hasMoved":true},null,null,null]]', '[{"from":"g5","to":"f7"}]', '{"pieceSquare":{"row":3,"col":6},"targetSquare":{"row":1,"col":5}}', datetime('now'), datetime('now')),
('knight-fork-1', 'Knight Fork', 'White to move. Use your knight to fork the king and rook simultaneously.', 'beginner', 'white', '[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,{"type":"rook","color":"black","hasMoved":true},null,null,null,{"type":"king","color":"black","hasMoved":true},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,{"type":"knight","color":"white","hasMoved":true},null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"type":"king","color":"white","hasMoved":true},null]]', '[{"from":"c3","to":"d5"}]', '{"pieceSquare":{"row":5,"col":2},"targetSquare":{"row":3,"col":3}}', datetime('now'), datetime('now')),
('skewer-queen-1', 'Royal Skewer', 'White to move. Skewer the king — when it moves, win the rook behind it.', 'intermediate', 'white', '[[null,null,null,null,{"type":"rook","color":"black","hasMoved":true},null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,{"type":"king","color":"black","hasMoved":true},null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[{"type":"queen","color":"white","hasMoved":true},null,null,null,null,null,{"type":"king","color":"white","hasMoved":true},null]]', '[{"from":"a1","to":"e1"}]', '{"pieceSquare":{"row":7,"col":0},"targetSquare":{"row":7,"col":4}}', datetime('now'), datetime('now')),
('discovered-attack-1', 'Discovered Attack', 'White to move. Move a piece to win the queen and reveal a devastating check from behind.', 'intermediate', 'white', '[[null,null,null,{"type":"king","color":"black","hasMoved":true},null,null,null,null],[null,null,{"type":"queen","color":"black","hasMoved":true},null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,{"type":"knight","color":"white","hasMoved":true},null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,{"type":"rook","color":"white","hasMoved":true},null,null,{"type":"king","color":"white","hasMoved":true},null]]', '[{"from":"d5","to":"c7"}]', '{"pieceSquare":{"row":3,"col":3},"targetSquare":{"row":1,"col":2}}', datetime('now'), datetime('now')),
('two-rooks-mate-1', 'Two Rooks Checkmate', 'White to move. Use your second rook to deliver checkmate on the back rank.', 'beginner', 'white', '[[{"type":"king","color":"black","hasMoved":true},null,null,null,null,null,null,{"type":"rook","color":"white","hasMoved":true}],[{"type":"pawn","color":"black","hasMoved":true},null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,{"type":"rook","color":"white","hasMoved":true},null,null,{"type":"king","color":"white","hasMoved":true},null,null,null]]', '[{"from":"b1","to":"b8"}]', '{"pieceSquare":{"row":7,"col":1},"targetSquare":{"row":0,"col":1}}', datetime('now'), datetime('now')),
('queen-mate-1', 'Queen Checkmate', 'White to move. Deliver checkmate with your queen.', 'beginner', 'white', '[[null,null,null,null,null,null,null,{"type":"king","color":"black","hasMoved":true}],[null,null,null,null,null,null,{"type":"pawn","color":"black","hasMoved":true},{"type":"pawn","color":"black","hasMoved":true}],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,{"type":"queen","color":"white","hasMoved":true},null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,{"type":"king","color":"white","hasMoved":true},null,null,null],[null,null,null,null,null,null,null,null]]', '[{"from":"d4","to":"d8"}]', '{"pieceSquare":{"row":4,"col":3},"targetSquare":{"row":0,"col":3}}', datetime('now'), datetime('now')),
('queen-fork-1', 'Queen Fork', 'White to move. Fork the king and rook with a single queen move.', 'intermediate', 'white', '[[null,null,null,null,null,null,null,null],[null,{"type":"king","color":"black","hasMoved":true},null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,{"type":"rook","color":"black","hasMoved":true}],[null,null,null,null,null,null,null,null],[null,{"type":"queen","color":"white","hasMoved":true},null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"type":"king","color":"white","hasMoved":true},null]]', '[{"from":"b3","to":"d5"}]', '{"pieceSquare":{"row":5,"col":1},"targetSquare":{"row":3,"col":3}}', datetime('now'), datetime('now')),
('rook-king-mate-1', 'Rook and King Mate', 'White to move. Use the rook to deliver checkmate — the king supports the final blow.', 'beginner', 'white', '[[{"type":"king","color":"black","hasMoved":true},null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,{"type":"king","color":"white","hasMoved":true},null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,{"type":"rook","color":"white","hasMoved":true}],[null,null,null,null,null,null,null,null]]', '[{"from":"h2","to":"h8"}]', '{"pieceSquare":{"row":6,"col":7},"targetSquare":{"row":0,"col":7}}', datetime('now'), datetime('now')),
('pin-and-win-1', 'Pin and Win', 'White to move. Pin the knight to the king — the pinned piece cannot move.', 'intermediate', 'white', '[[null,null,null,null,{"type":"king","color":"black","hasMoved":true},null,null,null],[null,null,null,null,null,null,null,null],[null,null,{"type":"knight","color":"black","hasMoved":true},null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"type":"bishop","color":"white","hasMoved":true},{"type":"king","color":"white","hasMoved":true},null]]', '[{"from":"f1","to":"b5"}]', '{"pieceSquare":{"row":7,"col":5},"targetSquare":{"row":3,"col":1}}', datetime('now'), datetime('now'))
ON CONFLICT(slug) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  difficulty = excluded.difficulty,
  player_color = excluded.player_color,
  initial_board = excluded.initial_board,
  solution = excluded.solution,
  hint = excluded.hint,
  updated_at = datetime('now');
